//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by C:\Printers\Printers1.0\trayicon.rc
//
#define IDS_DETAILS                     1000
#define ID_MYICON                       1500
#define IDD_DIALOG                      2500
#define IDC_DETAILS                     2501
#define IDC_STATIC1                     2502
#define IDC_STATIC2                     2503
#define IDC_STATIC0                     2504
#define IDM_ABOUT                       3500
#define IDM_EXIT                        3501
#define IDM_SEPARATOR                   3502
#define IDC_UPDATE                      4000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
